# Generated by Django 5.0.2 on 2024-02-24 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 12, 49, 32, 75749)),
        ),
    ]
