# Generated by Django 5.0.2 on 2024-02-24 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_zodiac_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
