# Generated by Django 5.0.2 on 2024-02-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_zodiac_start_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='trait_1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zodiac',
            name='trait_2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
