# Generated by Django 5.0.2 on 2024-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_zodiac_trait_1_zodiac_trait_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='trait_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='trait_2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
